apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: url-shortener
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      containers:
        - name: alloy
          image: grafana/alloy:v1.5.0
          args:
            - "run"
            - "/etc/alloy/config.alloy"
            - "--stability.level=public-preview"
          ports:
            - containerPort: 12345
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: varlog
              mountPath: /var/log
              readOnly: true
              mountPropagation: HostToContainer
            - name: varlibdocker
              mountPath: /var/lib/docker/containers
              readOnly: true
              mountPropagation: HostToContainer
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.1"
            limits:
              memory: "256Mi"
              cpu: "0.25"
      volumes:
        - name: config
          configMap:
            name: alloy-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdocker
          hostPath:
            path: /var/lib/docker/containers
