package com.shvmpk.shortener_service.service;

import tools.jackson.core.JacksonException;
import tools.jackson.databind.ObjectMapper;
import com.shvmpk.shortener_service.config.AppProperties;
import com.shvmpk.shortener_service.dto.ShortUrlRequest;
import com.shvmpk.shortener_service.dto.ShortUrlResponse;
import com.shvmpk.shortener_service.dto.ShortUrlUpdateRequest;
import com.shvmpk.shortener_service.dto.ShortUrlUpdateResponse;
import com.shvmpk.shortener_service.exception.*;
import com.shvmpk.shortener_service.model.ShortCode;
import com.shvmpk.shortener_service.model.UrlVersion;
import com.shvmpk.shortener_service.repository.UrlRepository;
import com.shvmpk.shortener_service.repository.UrlVersionRepository;
import com.shvmpk.shortener_service.util.*;
import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker;
import io.micrometer.core.instrument.MeterRegistry;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.DigestUtils;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.Optional;

@Slf4j
@Service
@RequiredArgsConstructor
public class ShortenService {

    private final AppProperties appProperties;
    private final UrlRepository urlRepository;
    private final UrlVersionRepository urlVersionRepository;
    private final ObjectMapper objectMapper;
    private final RedisTemplate<String, String> redisTemplate;
    private final ShortUrlGenerator shortUrlGenerator;
    private final PasswordService passwordService;
    private final UrlValidator urlValidator;
    private final MeterRegistry meterRegistry;

    @CircuitBreaker(name = "shortener-db", fallbackMethod = "resolveShortCodeFallback")
    public ShortCode resolveShortCodeOrAlias(String input) {
        if (input == null || input.trim().isEmpty()) {
            throw new IllegalArgumentException("Short code or alias must not be empty");
        }
        return urlRepository.findByShortCodeIgnoreCase(input)
                .or(() -> urlRepository.findByAliasIgnoreCase(input))
                .orElseThrow(() -> new UrlNotFoundException("Short code or alias not found: " + input));
    }

    private ShortCode resolveShortCodeFallback(String input, Throwable t) {
        log.warn("Circuit breaker fallback for resolveShortCodeOrAlias({}): {}", input, t.getMessage());
        if (t instanceof BaseApiException) {
            throw (BaseApiException) t;
        }
        throw new ServiceUnavailableException("Service temporarily unavailable. Please try again later.");
    }

    @Transactional
    @CircuitBreaker(name = "shortener-db", fallbackMethod = "shortenUrlFallback")
    public ShortUrlResponse shortenUrl(ShortUrlRequest request) {
        String inputUrl = request.getLongUrl().trim();
        log.info("Trimmed URL: {}", inputUrl);

        if (!urlValidator.isValid(inputUrl)) {
            throw new InvalidUrlException("Invalid URL format");
        }
        log.info("URL format validation passed");

        if (!urlValidator.isReachable(inputUrl)) {
            throw new InvalidUrlException("Unreachable URL");
        }
        log.info("URL reachability validation passed");

        String normalizedUrl = urlValidator.normalize(inputUrl);
        log.info("Normalized URL: {}", normalizedUrl);

        log.info("Validating alias....");
        String customAlias = request.getAlias();
        boolean isCustomAliasProvided = customAlias != null && !customAlias.isEmpty();
        if (isCustomAliasProvided) {
            customAlias = customAlias.trim();
            if (customAlias.length() > 20)
                throw new InvalidAliasException("Alias too long");
            if (urlRepository.existsByAliasIgnoreCase(customAlias)) {
                throw new UrlConflictException("Alias already exists");
            }
            log.info("Custom alias check passed");
        }

        log.info("Processing password protection....");
        String passwordHash = null;
        String autoGeneratedPassword = null;
        Boolean isProtected = request.getIsProtected();
        Boolean isAuto = request.getIsPasswordAutoGenerated();

        if (Boolean.TRUE.equals(isProtected)) {
            if (Boolean.TRUE.equals(isAuto)) {
                autoGeneratedPassword = passwordService.generateRandom(8);
                passwordHash = passwordService.hash(autoGeneratedPassword);
            } else {
                String rawPassword = request.getPassword();
                if (rawPassword == null || rawPassword.trim().isEmpty()) {
                    throw new InvalidPasswordException("Password required for protection");
                }
                passwordHash = passwordService.hash(rawPassword);
            }
        }

        log.info("Processing expiration....");
        Integer maxClicks = request.getMaxClicks();
        String expiresAtStr = request.getExpiresAt();
        boolean isClickBased = maxClicks != null && maxClicks > 0;

        if (isClickBased && expiresAtStr != null && !expiresAtStr.trim().isEmpty()) {
            throw new InvalidExpirationException("Choose either click-based or time-based expiration");
        }

        LocalDateTime expiry = null;
        if (!isClickBased) {
            expiry = (expiresAtStr != null && !expiresAtStr.trim().isEmpty())
                    ? LocalDateTime.parse(expiresAtStr)
                    : LocalDateTime.now().plusDays(1);
        }

        log.info("Processing caching and lookups....");
        String hash = DigestUtils.md5DigestAsHex(normalizedUrl.getBytes());
        String redisHashKey = "longUrl:" + hash;

        boolean requestedProtection = Boolean.TRUE.equals(isProtected);

        String cachedShortKey = redisTemplate.opsForValue().get(redisHashKey);
        if (cachedShortKey != null) {
            String cachedJson = redisTemplate.opsForValue().get("shortKey:" + cachedShortKey);
            if (cachedJson != null) {
                try {
                    ShortCode cachedObject = objectMapper.readValue(cachedJson, ShortCode.class);
                    if (requestedProtection == Boolean.TRUE.equals(cachedObject.getIsProtected())) {
                        meterRegistry.counter("shorten.cache.hit").increment();
                        return buildResponseFromEntity(cachedObject);
                    }
                    log.info("Cached URL protection ({}) differs from requested protection ({}); skipping cache",
                            cachedObject.getIsProtected(), requestedProtection);
                } catch (JacksonException e) {
                    log.warn("Failed to deserialize ShortUrl from Redis for key: {}", cachedShortKey, e);
                }
            }
        }

        // Cache stampede protection: serialize concurrent duplicate lookups
        String mutexKey = "lock:" + redisHashKey;
        boolean locked = Boolean.TRUE.equals(redisTemplate.opsForValue().setIfAbsent(mutexKey, "1", Duration.ofSeconds(2)));

        if (locked) {
            try {
                String recheck = redisTemplate.opsForValue().get(redisHashKey);
                if (recheck != null) {
                    String recheckJson = redisTemplate.opsForValue().get("shortKey:" + recheck);
                    if (recheckJson != null) {
                        ShortCode recheckObject = objectMapper.readValue(recheckJson, ShortCode.class);
                        if (requestedProtection == Boolean.TRUE.equals(recheckObject.getIsProtected())) {
                            meterRegistry.counter("shorten.cache.hit").increment();
                            return buildResponseFromEntity(recheckObject);
                        }
                    }
                }
            } catch (JacksonException e) {
                log.warn("Failed to deserialize ShortCode after lock", e);
            } finally {
                redisTemplate.delete(mutexKey);
            }
        } else {
            for (int i = 0; i < 5; i++) {
                try {
                    Thread.sleep(50);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    break;
                }
                String waiter = redisTemplate.opsForValue().get(redisHashKey);
                if (waiter != null) {
                    String waiterJson = redisTemplate.opsForValue().get("shortKey:" + waiter);
                    if (waiterJson != null) {
                        try {
                            ShortCode waiterObject = objectMapper.readValue(waiterJson, ShortCode.class);
                            if (requestedProtection == Boolean.TRUE.equals(waiterObject.getIsProtected())) {
                                return buildResponseFromEntity(waiterObject);
                            }
                        } catch (JacksonException e) {
                            log.warn("Failed to deserialize ShortCode after waiting", e);
                        }
                    }
                }
            }
        }

        Optional<ShortCode> existing = urlRepository.findFirstByOriginalUrlIgnoreCase(normalizedUrl);
        if (existing.isPresent()) {
            ShortCode found = existing.get();

            if (requestedProtection != Boolean.TRUE.equals(found.getIsProtected())) {
                throw new UrlConflictException(
                        "This URL has already been shortened with different protection settings");
            }

            String canonicalShortKey = found.getShortCode();

            redisTemplate.opsForValue().set(redisHashKey, canonicalShortKey, Duration.ofDays(1));
            try {
                String json = objectMapper.writeValueAsString(found);
                redisTemplate.opsForValue().set("shortKey:" + canonicalShortKey, json, Duration.ofDays(1));
            } catch (JacksonException e) {
                log.error("Failed to serialize ShortUrl to JSON", e);
            }

            meterRegistry.counter("shorten.cache.miss").increment();
            return buildResponseFromEntity(found);
        }

        String generatedShortCode = shortUrlGenerator.generate();

        if (urlRepository.existsByShortCodeIgnoreCase(generatedShortCode)) {
            throw new UrlConflictException("Short code collision");
        }

        try {
            ShortCode mapping = ShortCode.builder()
                    .originalUrl(normalizedUrl)
                    .shortCode(generatedShortCode)
                    .alias(isCustomAliasProvided ? customAlias : null)
                    .expiresAt(expiry)
                    .isProtected(Boolean.TRUE.equals(isProtected))
                    .isPasswordAutoGenerated(isAuto)
                    .password(passwordHash)
                    .maxClicks(maxClicks)
                    .uniqueVisitorCount(0)
                    .isClickBased(isClickBased)
                    .build();

            ShortCode savedMapping = urlRepository.save(mapping);

            UrlVersion initialVersion = UrlVersion.builder()
                    .versionNumber(1)
                    .originalUrl(normalizedUrl)
                    .alias(isCustomAliasProvided ? customAlias : null)
                    .isProtected(Boolean.TRUE.equals(isProtected))
                    .isPasswordAutoGenerated(isAuto)
                    .password(passwordHash)
                    .maxClicks(maxClicks)
                    .expiresAt(expiry)
                    .shortCode(savedMapping)
                    .build();

            UrlVersion savedVersion = urlVersionRepository.save(initialVersion);

            savedMapping.setCurrentVersion(savedVersion);
            ShortCode finalMapping = urlRepository.save(savedMapping);

            redisTemplate.opsForValue().set(redisHashKey, generatedShortCode, Duration.ofDays(1));
            try {
                String json = objectMapper.writeValueAsString(finalMapping);
                redisTemplate.opsForValue().set("shortKey:" + generatedShortCode, json, Duration.ofDays(1));
            } catch (JacksonException e) {
                log.warn("Failed to cache ShortUrl object", e);
            }

            meterRegistry.counter("shorten.url.created").increment();
            return buildResponseFromEntity(finalMapping);
        } catch (Exception e) {
            log.error("Failed to create short URL with versioning", e);
            throw new RuntimeException("Failed to create short URL", e);
        }
    }

    @Transactional
    @CircuitBreaker(name = "shortener-db", fallbackMethod = "updateUrlFallback")
    public ShortUrlUpdateResponse updateUrl(String canonicalShortCode, ShortUrlUpdateRequest updatedData) {
        ShortCode shortCode = urlRepository.findByShortCodeIgnoreCase(canonicalShortCode)
                .orElseThrow(() -> new UrlNotFoundException("Short code not found: " + canonicalShortCode));

        String oldAlias = shortCode.getAlias();
        String oldShortCode = shortCode.getShortCode();

        String newOriginalUrl = updatedData.getLongUrl() != null
                ? updatedData.getLongUrl().trim()
                : shortCode.getOriginalUrl();

        String newAlias = updatedData.getAlias() != null
                ? updatedData.getAlias().trim()
                : shortCode.getAlias();

        Boolean newIsProtected = updatedData.getIsProtected() != null
                ? updatedData.getIsProtected()
                : shortCode.getIsProtected();

        Boolean newIsAuto = updatedData.getIsPasswordAutoGenerated() != null
                ? updatedData.getIsPasswordAutoGenerated()
                : shortCode.getIsPasswordAutoGenerated();

        String newPasswordHash = shortCode.getPassword();

        if (Boolean.TRUE.equals(newIsProtected)) {
            if (Boolean.TRUE.equals(newIsAuto)) {
                String autoPassword = passwordService.generateRandom(8);
                newPasswordHash = passwordService.hash(autoPassword);
            } else if (updatedData.getPassword() != null && !updatedData.getPassword().trim().isEmpty()) {
                newPasswordHash = passwordService.hash(updatedData.getPassword());
            }
        } else {
            newPasswordHash = null;
        }

        boolean isClickBased = updatedData.getMaxClicks() != null;
        LocalDateTime newExpiry = null;

        if (!isClickBased && updatedData.getExpiresAt() != null && !updatedData.getExpiresAt().trim().isEmpty()) {
            newExpiry = LocalDateTime.parse(updatedData.getExpiresAt());
        } else if (shortCode.getExpiresAt() != null && updatedData.getExpiresAt() == null) {
            newExpiry = shortCode.getExpiresAt();
        }

        Integer newMaxClicks = isClickBased ? updatedData.getMaxClicks() : shortCode.getMaxClicks();

        boolean hasChanges = !shortCode.getOriginalUrl().equals(newOriginalUrl)
                || !equalsIgnoreCase(shortCode.getAlias(), newAlias)
                || !equalsNullable(shortCode.getIsProtected(), newIsProtected)
                || !equalsNullable(shortCode.getIsPasswordAutoGenerated(), newIsAuto)
                || !equalsNullable(shortCode.getPassword(), newPasswordHash)
                || !equalsNullable(shortCode.getMaxClicks(), newMaxClicks)
                || !equalsNullable(shortCode.getExpiresAt(), newExpiry);

        if (!hasChanges) {
            return buildUpdatedResponseFromEntity(shortCode);
        }

        evictCacheEntry(oldShortCode);
        if (oldAlias != null && !oldAlias.equalsIgnoreCase(newAlias)) {
            evictCacheEntry(oldAlias.toLowerCase());
        }

        int latestVersion = urlVersionRepository.findLatestVersionNumber(shortCode.getId());

        boolean shouldCreateBackup = false;

        if (latestVersion == 0) {
            shouldCreateBackup = true;
        } else {
            UrlVersion lastVersion = urlVersionRepository.findByShortCodeIdAndVersionNumber(
                    shortCode.getId(), latestVersion);

            if (lastVersion != null) {
                boolean currentStateDiffersFromLastVersion =
                        !shortCode.getOriginalUrl().equals(lastVersion.getOriginalUrl())
                                || !equalsIgnoreCase(shortCode.getAlias(), lastVersion.getAlias())
                                || !equalsNullable(shortCode.getIsProtected(), lastVersion.getIsProtected())
                                || !equalsNullable(shortCode.getIsPasswordAutoGenerated(), lastVersion.getIsPasswordAutoGenerated())
                                || !equalsNullable(shortCode.getPassword(), lastVersion.getPassword())
                                || !equalsNullable(shortCode.getMaxClicks(), lastVersion.getMaxClicks())
                                || !equalsNullable(shortCode.getExpiresAt(), lastVersion.getExpiresAt());

                shouldCreateBackup = currentStateDiffersFromLastVersion;
            }
        }

        int nextVersionNumber = latestVersion + 1;

        if (shouldCreateBackup) {
            UrlVersion backupVersion = UrlVersion.builder()
                    .shortCode(shortCode)
                    .versionNumber(nextVersionNumber)
                    .originalUrl(shortCode.getOriginalUrl())
                    .alias(shortCode.getAlias())
                    .isProtected(shortCode.getIsProtected())
                    .isPasswordAutoGenerated(shortCode.getIsPasswordAutoGenerated())
                    .password(shortCode.getPassword())
                    .maxClicks(shortCode.getMaxClicks())
                    .expiresAt(shortCode.getExpiresAt())
                    .rollbackFromVersion(null)
                    .isRollback(false)
                    .build();
            urlVersionRepository.save(backupVersion);
            nextVersionNumber++;
        }

        shortCode.setOriginalUrl(newOriginalUrl);
        shortCode.setAlias(newAlias);
        shortCode.setIsProtected(newIsProtected);
        shortCode.setIsPasswordAutoGenerated(newIsAuto);
        shortCode.setPassword(newPasswordHash);
        shortCode.setMaxClicks(newMaxClicks);
        shortCode.setExpiresAt(newExpiry);
        shortCode.setIsClickBased(isClickBased);
        urlRepository.save(shortCode);

        UrlVersion newVersion = UrlVersion.builder()
                .shortCode(shortCode)
                .versionNumber(nextVersionNumber)
                .originalUrl(newOriginalUrl)
                .alias(newAlias)
                .isProtected(newIsProtected)
                .isPasswordAutoGenerated(newIsAuto)
                .password(newPasswordHash)
                .maxClicks(newMaxClicks)
                .expiresAt(newExpiry)
                .rollbackFromVersion(null)
                .isRollback(false)
                .build();
        UrlVersion savedVersion = urlVersionRepository.save(newVersion);

        shortCode.setCurrentVersion(savedVersion);
        urlRepository.save(shortCode);

        try {
            String serialized = objectMapper.writeValueAsString(shortCode);
            redisTemplate.opsForValue().set("shortKey:" + shortCode.getShortCode(), serialized, Duration.ofDays(1));
            if (newAlias != null) {
                redisTemplate.opsForValue().set("shortKey:" + newAlias.toLowerCase(), serialized, Duration.ofDays(1));
            }
        } catch (JacksonException e) {
            log.error("Failed to serialize ShortCode for caching", e);
        }

        String redirectKey = "redirect:" + shortCode.getShortCode();
        Duration ttl = computeTtl(newExpiry);
        redisTemplate.opsForValue().set(redirectKey, shortCode.getOriginalUrl(), ttl);
        if (newAlias != null) {
            redisTemplate.opsForValue().set("redirect:" + newAlias.toLowerCase(), shortCode.getOriginalUrl(), ttl);
        }

        return buildUpdatedResponseFromEntity(shortCode);
    }

    @CircuitBreaker(name = "shortener-db", fallbackMethod = "deleteUrlFallback")
    public void deleteUrl(String canonicalShortCode) {
        ShortCode mapping = urlRepository.findByShortCodeIgnoreCase(canonicalShortCode)
                .orElseThrow(() -> new UrlNotFoundException("Short code not found: " + canonicalShortCode));

        urlRepository.delete(mapping);

        String hash = DigestUtils.md5DigestAsHex(mapping.getOriginalUrl().getBytes());
        redisTemplate.delete("longUrl:" + hash);
        evictCacheEntry(canonicalShortCode);
        if (mapping.getAlias() != null) {
            evictCacheEntry(mapping.getAlias().toLowerCase());
        }

        log.info("Deleted short URL: {}", canonicalShortCode);
    }

    private ShortUrlResponse shortenUrlFallback(ShortUrlRequest request, Throwable t) {
        log.warn("Circuit breaker fallback for shortenUrl: {}", t.getMessage());
        if (t instanceof BaseApiException) {
            throw (BaseApiException) t;
        }
        throw new ServiceUnavailableException("Service temporarily unavailable. Please try again later.");
    }

    private ShortUrlUpdateResponse updateUrlFallback(String canonicalShortCode, ShortUrlUpdateRequest updatedData, Throwable t) {
        log.warn("Circuit breaker fallback for updateUrl({}): {}", canonicalShortCode, t.getMessage());
        if (t instanceof BaseApiException) {
            throw (BaseApiException) t;
        }
        throw new ServiceUnavailableException("Service temporarily unavailable. Please try again later.");
    }

    private void deleteUrlFallback(String canonicalShortCode, Throwable t) {
        log.warn("Circuit breaker fallback for deleteUrl({}): {}", canonicalShortCode, t.getMessage());
        if (t instanceof BaseApiException) {
            throw (BaseApiException) t;
        }
        throw new ServiceUnavailableException("Service temporarily unavailable. Please try again later.");
    }

    private void evictCacheEntry(String key) {
        redisTemplate.delete("shortKey:" + key);
        redisTemplate.delete("redirect:" + key);
    }

    private Duration computeTtl(LocalDateTime expiresAt) {
        if (expiresAt == null) {
            return Duration.ofDays(7);
        }
        Duration d = Duration.between(LocalDateTime.now(), expiresAt);
        return d.isNegative() ? Duration.ZERO : d;
    }

    private ShortUrlUpdateResponse buildUpdatedResponseFromEntity(ShortCode entity) {
        String shortKey = (entity.getAlias() != null) ? entity.getAlias() : entity.getShortCode();
        String expiration = entity.getIsClickBased() != null && entity.getIsClickBased()
                ? "Expires after " + entity.getMaxClicks() + " clicks"
                : entity.getExpiresAt() != null ? "Expires at " + entity.getExpiresAt().toString() : "No expiration";
        String alias = entity.getAlias() != null ? appProperties.baseUrl() + "/" + entity.getAlias() : null;

        return ShortUrlUpdateResponse.builder()
                .originalUrl(entity.getOriginalUrl())
                .shortUrl(appProperties.baseUrl() + "/" + entity.getShortCode())
                .aliasUrl(alias)
                .qrCodeUrl(appProperties.baseUrl() + "/qr/" + shortKey)
                .isProtected(entity.getIsProtected())
                .isPasswordAutoGenerated(entity.getIsPasswordAutoGenerated())
                .password(entity.getPassword())
                .expiresAt(expiration)
                .maxClicksAllowed(entity.getMaxClicks())
                .currentVersion(entity.getCurrentVersion() != null ? entity.getCurrentVersion().getVersionNumber() : null)
                .build();
    }

    private ShortUrlResponse buildResponseFromEntity(ShortCode entity) {
        String shortKey = (entity.getAlias() != null) ? entity.getAlias() : entity.getShortCode();
        String expiration = entity.getIsClickBased() != null && entity.getIsClickBased()
                ? "Expires after " + entity.getMaxClicks() + " clicks"
                : entity.getExpiresAt() != null ? "Expires at " + entity.getExpiresAt().toString() : "No expiration";
        String alias = entity.getAlias() != null ? appProperties.baseUrl() + "/" + entity.getAlias() : null;
        return ShortUrlResponse.builder()
                .shortUrl(appProperties.baseUrl() + "/" + entity.getShortCode())
                .aliasUrl(alias)
                .qrCodeUrl(appProperties.baseUrl() + "/qr/" + shortKey)
                .expiresAt(expiration)
                .maxClicksAllowed(entity.getMaxClicks())
                .passwordProtected(entity.getIsProtected())
                .build();
    }

    private boolean equalsNullable(Object a, Object b) {
        return a == null ? b == null : a.equals(b);
    }

    private boolean equalsIgnoreCase(String a, String b) {
        return a == null ? b == null : a.equalsIgnoreCase(b);
    }
}
