package com.shvmpk.shortener_service.service;

import com.shvmpk.shortener_service.dto.UrlVersionResponse;
import com.shvmpk.shortener_service.exception.*;
import com.shvmpk.shortener_service.model.ShortCode;
import com.shvmpk.shortener_service.model.UrlVersion;
import com.shvmpk.shortener_service.repository.UrlRepository;
import com.shvmpk.shortener_service.repository.UrlVersionRepository;
import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@Slf4j
@Service
@RequiredArgsConstructor
public class UrlVersionService {
    private final UrlVersionRepository urlVersionRepository;
    private final UrlRepository urlRepository;
    private final RedisTemplate<String, String> redisTemplate;

    public List<UrlVersionResponse> getVersionsByShortCodeOrAlias(ShortCode shortCode) {
        List<UrlVersion> versions = urlVersionRepository.findByShortCodeOrderByVersionNumberDesc(shortCode);
        return versions.stream()
                .map(this::convertToResponse)
                .toList();
    }

    @Transactional
    @CircuitBreaker(name = "shortener-db", fallbackMethod = "rollbackFallback")
    public UrlVersionResponse rollbackToVersion(ShortCode shortCode, Integer versionNumber) {
        UrlVersion targetVersion = urlVersionRepository.findByShortCodeAndVersionNumber(shortCode, versionNumber)
                .orElseThrow(() -> new UrlNotFoundException("Version not found"));

        UrlVersion backupVersion = UrlVersion.builder()
                .shortCode(shortCode)
                .versionNumber(urlVersionRepository.findLatestVersionNumber(shortCode.getId()) + 1)
                .originalUrl(shortCode.getOriginalUrl())
                .alias(shortCode.getAlias())
                .isProtected(shortCode.getIsProtected())
                .isPasswordAutoGenerated(shortCode.getIsPasswordAutoGenerated())
                .password(shortCode.getPassword())
                .maxClicks(shortCode.getMaxClicks())
                .expiresAt(shortCode.getExpiresAt())
                .build();
        urlVersionRepository.save(backupVersion);

        shortCode.setOriginalUrl(targetVersion.getOriginalUrl());
        shortCode.setAlias(targetVersion.getAlias());
        shortCode.setIsProtected(targetVersion.getIsProtected());
        shortCode.setIsPasswordAutoGenerated(targetVersion.getIsPasswordAutoGenerated());
        shortCode.setPassword(targetVersion.getPassword());
        shortCode.setMaxClicks(targetVersion.getMaxClicks());
        shortCode.setExpiresAt(targetVersion.getExpiresAt());

        UrlVersion rollbackVersion = UrlVersion.builder()
                .shortCode(shortCode)
                .versionNumber(urlVersionRepository.findLatestVersionNumber(shortCode.getId()) + 1)
                .originalUrl(targetVersion.getOriginalUrl())
                .alias(targetVersion.getAlias())
                .isProtected(targetVersion.getIsProtected())
                .isPasswordAutoGenerated(targetVersion.getIsPasswordAutoGenerated())
                .password(targetVersion.getPassword())
                .maxClicks(targetVersion.getMaxClicks())
                .expiresAt(targetVersion.getExpiresAt())
                .rollbackFromVersion(targetVersion.getVersionNumber())
                .isRollback(true)
                .build();

        UrlVersion savedRollback = urlVersionRepository.save(rollbackVersion);

        shortCode.setCurrentVersion(savedRollback);
        urlRepository.save(shortCode);

        evictCacheEntry(shortCode.getShortCode());
        if (shortCode.getAlias() != null) {
            evictCacheEntry(shortCode.getAlias().toLowerCase());
        }

        return convertToResponse(savedRollback);
    }

    private UrlVersionResponse convertToResponse(UrlVersion version) {
        return UrlVersionResponse.builder()
                .versionNumber(version.getVersionNumber())
                .originalUrl(version.getOriginalUrl())
                .alias(version.getAlias())
                .isProtected(version.getIsProtected())
                .isPasswordAutoGenerated(version.getIsPasswordAutoGenerated())
                .password(version.getPassword())
                .maxClicks(version.getMaxClicks() != null ? version.getMaxClicks().longValue() : null)
                .expiresAt(version.getExpiresAt())
                .createdAt(version.getVersionCreatedAt())
                .rollbackFromVersion(version.getRollbackFromVersion())
                .isRollback(version.getIsRollback())
                .build();
    }

    public UrlVersionResponse getCurrentVersion(ShortCode shortCode) {
        UrlVersion current = shortCode.getCurrentVersion();
        if (current == null) {
            throw new UrlNotFoundException("Current version not set");
        }
        return mapToResponse(current);
    }

    public Map<String, Map<String, Object>> compareVersions(ShortCode shortCode, Integer from, Integer to) {
        UrlVersion v1 = urlVersionRepository.findByShortCodeAndVersionNumber(shortCode, from)
                .orElseThrow(() -> new UrlNotFoundException("From version not found"));
        UrlVersion v2 = urlVersionRepository.findByShortCodeAndVersionNumber(shortCode, to)
                .orElseThrow(() -> new UrlNotFoundException("To version not found"));

        Map<String, Map<String, Object>> diff = new HashMap<>();
        compareField("originalUrl", v1.getOriginalUrl(), v2.getOriginalUrl(), diff);
        compareField("alias", v1.getAlias(), v2.getAlias(), diff);
        compareField("isProtected", v1.getIsProtected(), v2.getIsProtected(), diff);
        compareField("isPasswordAutoGenerated", v1.getIsPasswordAutoGenerated(), v2.getIsPasswordAutoGenerated(), diff);
        compareField("password", v1.getPassword(), v2.getPassword(), diff);
        compareField("maxClicks", v1.getMaxClicks(), v2.getMaxClicks(), diff);
        compareField("expiresAt", v1.getExpiresAt(), v2.getExpiresAt(), diff);
        return diff;
    }

    private UrlVersionResponse mapToResponse(UrlVersion version) {
        return UrlVersionResponse.builder()
                .versionNumber(version.getVersionNumber())
                .originalUrl(version.getOriginalUrl())
                .alias(version.getAlias())
                .isProtected(version.getIsProtected())
                .isPasswordAutoGenerated(version.getIsPasswordAutoGenerated())
                .password(version.getPassword())
                .maxClicks(version.getMaxClicks() != null ? version.getMaxClicks().longValue() : null)
                .expiresAt(version.getExpiresAt())
                .createdAt(version.getVersionCreatedAt())
                .rollbackFromVersion(version.getRollbackFromVersion())
                .isRollback(version.getIsRollback())
                .build();
    }

    private UrlVersionResponse rollbackFallback(ShortCode shortCode, Integer versionNumber, Throwable t) {
        log.warn("Circuit breaker fallback for rollbackToVersion({}, {}): {}", shortCode.getShortCode(), versionNumber, t.getMessage());
        if (t instanceof BaseApiException) {
            throw (BaseApiException) t;
        }
        throw new ServiceUnavailableException("Service temporarily unavailable. Please try again later.");
    }

    private String deleteVersionFallback(ShortCode shortCode, Integer versionNumber, Throwable t) {
        log.warn("Circuit breaker fallback for deleteSpecificVersion({}, {}): {}", shortCode.getShortCode(), versionNumber, t.getMessage());
        if (t instanceof BaseApiException) {
            throw (BaseApiException) t;
        }
        throw new ServiceUnavailableException("Service temporarily unavailable. Please try again later.");
    }

    private void evictCacheEntry(String key) {
        redisTemplate.delete("shortKey:" + key);
        redisTemplate.delete("redirect:" + key);
    }

    private void compareField(String field, Object v1, Object v2, Map<String, Map<String, Object>> diff) {
        if (!Objects.equals(v1, v2)) {
            Map<String, Object> change = new HashMap<>();
            change.put("from", v1);
            change.put("to", v2);
            diff.put(field, change);
        }
    }

    @Transactional
    @CircuitBreaker(name = "shortener-db", fallbackMethod = "deleteVersionFallback")
    public String deleteSpecificVersion(ShortCode shortCode, Integer versionNumber) {
        try {
            urlVersionRepository.deleteByShortCodeAndVersionNumber(shortCode, versionNumber);
            return "Successfully deleted version " + versionNumber;
        } catch (Exception e) {
            throw new RuntimeException("Failed to delete version " + versionNumber, e);
        }
    }
}
