package com.shvmpk.redirect_service.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
@EqualsAndHashCode
@Table(name = "short_code")
public class ShortCode {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String shortCode;

    @Column(nullable = false)
    private String originalUrl;

    @Column(unique = true)
    private String alias;

    @Column(nullable = false)
    @Builder.Default
    private Boolean isProtected = false;

    private Boolean isPasswordAutoGenerated;

    private String password;

    private Integer maxClicks;

    @Builder.Default
    private Integer uniqueVisitorCount = 0;

    private LocalDateTime expiresAt;

    @Builder.Default
    private Boolean isClickBased = false;

    @CreationTimestamp
    private LocalDateTime createdAt;

    private Long currentVersionId;
}
