CREATE TABLE IF NOT EXISTS analytics (
    id BIGSERIAL PRIMARY KEY,
    short_code VARCHAR(255) NOT NULL,
    access_date DATE NOT NULL,
    total_visit_count INTEGER DEFAULT 0,
    browser_visit_counts TEXT,
    device_type_visit_counts TEXT,
    os_visit_counts TEXT,
    browser_last_seen TEXT,
    device_last_seen TEXT,
    country VARCHAR(255),
    city VARCHAR(255),
    region VARCHAR(255),
    continent VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    asn BIGINT,
    isp VARCHAR(255),
    organization VARCHAR(255),
    referer VARCHAR(255),
    utm_source VARCHAR(255),
    utm_medium VARCHAR(255),
    utm_campaign VARCHAR(255),
    utm_term VARCHAR(255),
    is_bot BOOLEAN DEFAULT FALSE,
    user_agent VARCHAR(255),
    recent_access_times TEXT,
    clicks_last10_min INTEGER DEFAULT 0,
    clicks_last1_hour INTEGER DEFAULT 0,
    last_access_time TIMESTAMP,
    version BIGINT DEFAULT 0,
    CONSTRAINT uq_analytics_short_code_access_date UNIQUE (short_code, access_date)
);
