package com.shvmpk.shortener_service.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = {"shortCode"})
@EqualsAndHashCode(exclude = {"shortCode"})
public class UrlVersion {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private Integer versionNumber;

    private String originalUrl;

    private String alias;

    private Boolean isProtected;

    private Boolean isPasswordAutoGenerated;

    private String password;

    private Integer maxClicks;

    private LocalDateTime expiresAt;

    @CreationTimestamp
    private LocalDateTime versionCreatedAt;

    @Column(nullable = true)
    private Integer rollbackFromVersion;

    @Builder.Default
    private Boolean isRollback = false;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "short_code_id", nullable = false)
    @JsonBackReference
    private ShortCode shortCode;
}
