package com.shvmpk.shortener_service.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ShortUrlUpdateResponse {
    private String originalUrl;
    private String shortUrl;
    private String aliasUrl;
    private String qrCodeUrl;
    private Boolean isProtected;
    private Boolean isPasswordAutoGenerated;
    private String password;
    private String expiresAt;
    private Integer maxClicksAllowed;
    private Integer currentVersion;
}
