package com.shvmpk.shortener_service.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class UrlVersionResponse {
    private Integer versionNumber;
    private String originalUrl;
    private String alias;
    private Boolean isProtected;
    private Boolean isPasswordAutoGenerated;
    private String password;
    private Long maxClicks;
    private LocalDateTime expiresAt;
    private LocalDateTime createdAt;

    private Integer rollbackFromVersion;
    private Boolean isRollback;
}
