apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener
  namespace: url-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shortener
  template:
    metadata:
      labels:
        app: shortener
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: shortener
          image: url-shortener/shortener:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.25"
            limits:
              memory: "512Mi"
              cpu: "0.5"
